-- JSONDB TABLE
DROP TABLE IF EXISTS jsonDB CASCADE;

CREATE TABLE jsonDB (
    id SERIAL PRIMARY KEY,
    resume_id INT NOT NULL REFERENCES resumes(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parsed_json JSONB NOT NULL,
    ml_metadata JSONB DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
