-- USER_RESUMES BRIDGE TABLE
DROP TABLE IF EXISTS user_resumes CASCADE;

CREATE TABLE user_resumes (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    resume_id INT NOT NULL REFERENCES resumes(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
